//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AccountResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.AccountResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆盖当前线程的 CurrentUICulture 属性
        ///   使用此强类型的资源类的资源查找。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///  查找类似 廠區門禁 的本地化字符串。
        /// </summary>
        internal static string Access {
            get {
                return ResourceManager.GetString("Access", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 P4以上稽核報表 的本地化字符串。
        /// </summary>
        internal static string AttendanceAudit {
            get {
                return ResourceManager.GetString("AttendanceAudit", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 系統管理 的本地化字符串。
        /// </summary>
        internal static string AttendanceManage {
            get {
                return ResourceManager.GetString("AttendanceManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 刪除 的本地化字符串。
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 部門 的本地化字符串。
        /// </summary>
        internal static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 描述 的本地化字符串。
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 編輯 的本地化字符串。
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 姓名 的本地化字符串。
        /// </summary>
        internal static string EmpName {
            get {
                return ResourceManager.GetString("EmpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 工號 的本地化字符串。
        /// </summary>
        internal static string EmpNo {
            get {
                return ResourceManager.GetString("EmpNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 英文 的本地化字符串。
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 工廠 的本地化字符串。
        /// </summary>
        internal static string Factory {
            get {
                return ResourceManager.GetString("Factory", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 首頁 的本地化字符串。
        /// </summary>
        internal static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 幫助 的本地化字符串。
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 人事管理 的本地化字符串。
        /// </summary>
        internal static string HumanResources {
            get {
                return ResourceManager.GetString("HumanResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 最後一頁 的本地化字符串。
        /// </summary>
        internal static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 退出 的本地化字符串。
        /// </summary>
        internal static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 郵箱 的本地化字符串。
        /// </summary>
        internal static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 頁面管理 的本地化字符串。
        /// </summary>
        internal static string menuManagement {
            get {
                return ResourceManager.GetString("menuManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 菜單 的本地化字符串。
        /// </summary>
        internal static string menus {
            get {
                return ResourceManager.GetString("menus", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 菜單權限 的本地化字符串。
        /// </summary>
        internal static string MenuSecurityManage {
            get {
                return ResourceManager.GetString("MenuSecurityManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 名稱 的本地化字符串。
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 新增菜單 的本地化字符串。
        /// </summary>
        internal static string NewMenu {
            get {
                return ResourceManager.GetString("NewMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 下一頁 的本地化字符串。
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 編號 的本地化字符串。
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 其他報表 的本地化字符串。
        /// </summary>
        internal static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 車間門禁 的本地化字符串。
        /// </summary>
        internal static string Plant {
            get {
                return ResourceManager.GetString("Plant", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 上一頁 的本地化字符串。
        /// </summary>
        internal static string Prev {
            get {
                return ResourceManager.GetString("Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 執行程序 的本地化字符串。
        /// </summary>
        internal static string ProgramManagement {
            get {
                return ResourceManager.GetString("ProgramManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 刷新 的本地化字符串。
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 用戶組管理 的本地化字符串。
        /// </summary>
        internal static string securityGroupManagement {
            get {
                return ResourceManager.GetString("securityGroupManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 簡體中文 的本地化字符串。
        /// </summary>
        internal static string Simplified {
            get {
                return ResourceManager.GetString("Simplified", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 系統管理 的本地化字符串。
        /// </summary>
        internal static string systemManagement {
            get {
                return ResourceManager.GetString("systemManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 繁體中文 的本地化字符串。
        /// </summary>
        internal static string Traditional {
            get {
                return ResourceManager.GetString("Traditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 用戶管理 的本地化字符串。
        /// </summary>
        internal static string UserManagement {
            get {
                return ResourceManager.GetString("UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 用戶權限 的本地化字符串。
        /// </summary>
        internal static string UserSecurityManagement {
            get {
                return ResourceManager.GetString("UserSecurityManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 歡迎您 的本地化字符串。
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
